; This is a lazy sunday
(defvar global_credits 0)
(
  defun lazy()
  (princ "-------------------")
  (terpri)
  (princ "Lazy sunday Dude.")
  (terpri)
  (princ "-------------------")
)
(
  defun wash()
  (princ "-------------------")
  (terpri)
  (princ "Use Washing machine.")
  (terpri)
  (princ "-------------------")
)
(
  defun toilet_clean()
  (princ "-------------------")
  (terpri)
  (princ "Clean the toilet using brush.")
  (terpri)
  (princ "-------------------")
)
(
  defun call_parents()
  (princ "-------------------")
  (terpri)
  (princ "In Morning everyone is in his or her best moods. So are parents.")
  (terpri)
  (princ "-------------------")
)
(
  defun call_friends()
  (princ "-------------------")
  (terpri)
  (princ "Use the evening or the afternoon. Also ask other friends numbers.")
  (terpri)
  (princ "-------------------")
)
(
  defun call_pugi()
  (princ "-------------------")
  (terpri)
  (princ "Well !! Call Pugi. It is duty.")
  (terpri)
  (princ "-------------------")
)
(
  defun reload_refrigerator()
  (princ "-------------------")
  (terpri)
  (princ "Use big basket if and when required. Or the local mandi is polythene friendly.")
  (terpri)
  (princ "-------------------")
)
(
  defun iron_clothes()
  (princ "-------------------")
  (terpri)
  (princ "Use the local shop.")
  (terpri)
  (princ "-------------------")
)
(
  defun pay_bills()
  (princ "-------------------")
  (terpri)
  (princ "Clear the bills at the earliest. Especially the American Express.")
  (terpri)
  (princ "-------------------")
)
(
  defun main()  
  (loop
   (defvar choice -1)
   (terpri)(terpri)
   (princ "This is kind of a menu.")
   (terpri)(terpri)
   (princ "1. Wash the clothes")(terpri)
   (princ "2. Clean the bathroom")(terpri)
   (princ "3. Call up parents")(terpri)
   (princ "4. Call up friends or colleagues")(terpri)
   (princ "5. Call up Pugi")(terpri)
   (princ "6. Reload the refrigerator")(terpri)
   (princ "7. Iron the clothes")(terpri)
   (princ "8. Clear the bills.")(terpri)
   (princ "9. Exit.")(terpri)
   (setq choice (read))
   ;(princ (list "your choice is" choice))
   (terpri)(terpri)
    (cond
    ((= choice 1) (wash))
    ((= choice 2) (toilet_clean))
    ((= choice 3) (call_parents))
    ((= choice 4) (call_friends))
    ((= choice 5) (call_pugi))
    ((= choice 6) (reload_refrigerator))
    ((= choice 7) (iron_clothes))
    ((= choice 8) (pay_bills))
    ((= choice 9) (return))
    ((= choice 0) (lazy))
   )
  )  
)
(main)